SOCIAL_AUTH_TWITTER_KEY = '9AgAg61AFuOx90UVVo3tvwG13'
SOCIAL_AUTH_TWITTER_SECRET = 'jROnu5N3mof54ALBIGtckbv80mO6AxER3Fp8WG3YO3fDBdSZkS'
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/home/'
SOCIAL_AUTH_LOGIN_URL = '/'