# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-20 04:41
from __future__ import unicode_literals

import Quiz_arena.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0004_auto_20160423_0400'),
        ('Quiz_arena', '0002_auto_20160716_0618'),
    ]

    operations = [
        migrations.CreateModel(
            name='skill',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('proficiency', models.IntegerField(default=50)),
            ],
        ),
        migrations.AddField(
            model_name='user_info',
            name='about_me',
            field=models.TextField(default='I am a quizer !'),
        ),
        migrations.AddField(
            model_name='user_info',
            name='profile_pic',
            field=models.ImageField(default='index.png', upload_to=Quiz_arena.models.filepath),
        ),
        migrations.AddField(
            model_name='user_info',
            name='social_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='default.UserSocialAuth'),
        ),
        migrations.AddField(
            model_name='user_info',
            name='skills',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz_arena.skill'),
        ),
    ]
