# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-20 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_arena', '0003_auto_20160720_0441'),
    ]

    operations = [
        migrations.CreateModel(
            name='options',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False)),
                ('option_quote', models.CharField(max_length=250)),
                ('option_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('s_c', 'single_correct'), ('m_c', 'multiple_correct')], default='mcq', max_length=10)),
                ('question_title', models.TextField()),
                ('answer', models.CharField(max_length=50, null=True)),
                ('correct_message', models.TextField(null=True)),
                ('Incorrect_message', models.TextField(null=True)),
                ('options', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz_arena.options')),
            ],
        ),
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('beginning_quote', models.TextField(null=True)),
                ('end_quote', models.TextField(null=True)),
                ('number_of_questions', models.IntegerField(default=10)),
                ('duration', models.IntegerField(default=30)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('questions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz_arena.questions')),
            ],
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='skills',
        ),
        migrations.DeleteModel(
            name='skill',
        ),
        migrations.AddField(
            model_name='user_info',
            name='quizes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz_arena.quiz'),
        ),
    ]
