# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-20 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_arena', '0005_auto_20160720_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='creater',
            new_name='creator',
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_type',
            field=models.CharField(choices=[('sc', 'sc'), ('mc', 'mc')], default='sc', max_length=10),
        ),
    ]
