# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-21 07:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Quiz_arena', '0007_auto_20160721_0505'),
    ]

    operations = [
        migrations.CreateModel(
            name='option_response',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz_arena.options')),
            ],
        ),
        migrations.CreateModel(
            name='question_response',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz_arena.questions')),
            ],
        ),
        migrations.CreateModel(
            name='quiz_response',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='quiz',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz_response',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz_arena.quiz'),
        ),
        migrations.AddField(
            model_name='quiz_response',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question_response',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz_arena.quiz_response'),
        ),
        migrations.AddField(
            model_name='option_response',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz_arena.question_response'),
        ),
    ]
