# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-29 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_arena', '0008_auto_20160721_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_response',
            name='time_of_attempt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
